# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Velox backend Dependency Cache

on:
  push:
    branches:
      - 'main'

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  CCACHE_DIR: "${{ github.workspace }}/.ccache"

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  cache-native-lib-centos-7:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Get Ccache
        uses: actions/cache/restore@v3
        with:
          path: '${{ env.CCACHE_DIR }}'
          key: ccache-centos7-release-default-${{github.sha}}
          restore-keys: |
            ccache-centos7-release-default
      - name: Build Gluten native libraries
        run: |
          docker run -v $GITHUB_WORKSPACE:/work -w /work apache/gluten:vcpkg-centos-7 bash -c "
            export CCACHE_DIR=/work/.ccache
            mkdir -p /work/.ccache
            bash dev/ci-velox-buildstatic-centos-7.sh
          "
      - name: Save Ccache
        uses: actions/cache/save@v3
        id: ccache
        with:
          path: '${{ env.CCACHE_DIR }}'
          key: ccache-centos7-release-default-${{github.sha}}

  cache-native-lib-centos-8:
    runs-on: ubuntu-22.04
    container: apache/gluten:centos-8-jdk8
    steps:
      - uses: actions/checkout@v2
      - name: Get Ccache
        uses: actions/cache/restore@v3
        with:
          path: '${{ env.CCACHE_DIR }}'
          key: ccache-centos8-release-default-${{github.sha}}
          restore-keys: |
            ccache-centos8-release-default
      - name: Build Gluten native libraries
        run: |
          df -a
          bash dev/ci-velox-buildshared-centos-8.sh
          ccache -s
      - name: Save Ccache
        uses: actions/cache/save@v3
        id: ccache
        with:
          path: '${{ env.CCACHE_DIR }}'
          key: ccache-centos8-release-default-${{github.sha}}

  # ccache-native-lib-ubuntu-velox-ut:
  #   runs-on: ubuntu-22.04
  #   env:
  #     CCACHE_DIR: "${{ github.workspace }}/.ccache"
  #   container: ghcr.io/facebookincubator/velox-dev:amd64-ubuntu-22.04-avx
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Get Ccache
  #       uses: actions/cache/restore@v3
  #       with:
  #         path: '${{ env.CCACHE_DIR }}'
  #         key: ccache-ubuntu-release-default
  #     - name: Ensure Cache Dirs Exists
  #       working-directory: ${{ github.workspace }}
  #       run: |
  #         mkdir -p '${{ env.CCACHE_DIR }}'
  #     - name: Build Gluten native libraries
  #       run: |
  #         rm -rf /opt/miniconda-for-velox/
  #         cd ep/build-velox/src && \
  #         ./get_velox.sh
  #         cd ../build/velox_ep/
  #         make EXTRA_CMAKE_FLAGS="-DVELOX_ENABLE_PARQUET=ON -DVELOX_BUILD_TESTING=ON -DVELOX_BUILD_TEST_UTILS=ON" 

  #     - name: CCache after
  #       run: |
  #         ccache -vs

  #     - uses: actions/cache/save@v3
  #       with:
  #         path: '${{ env.CCACHE_DIR }}'
  #         key: ccache-ubuntu-release-default
#  ccache-native-lib-centos-velox-ut:
#    runs-on: ubuntu-22.04
#    env:
#      CCACHE_DIR: "${{ github.workspace }}/.ccache"
#    container: ghcr.io/facebookincubator/velox-dev:centos8
#    steps:
#      - uses: actions/checkout@v2
#      - name: Setup java and maven
#        run: |
#          yum install sudo patch java-1.8.0-openjdk-devel wget -y && \
#          wget https://downloads.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
#          tar -xvf apache-maven-3.8.8-bin.tar.gz
#          mv apache-maven-3.8.8 /usr/lib/maven
#      - name: Get Ccache
#        uses: actions/cache/restore@v3
#        with:
#          path: '${{ env.CCACHE_DIR }}'
#          key: ccache-centos-release-default
#      - name: Ensure Cache Dirs Exists
#        working-directory: ${{ github.workspace }}
#        run: |
#          mkdir -p '${{ env.CCACHE_DIR }}'
#      - name: Build Gluten native libraries
#        run: |
#          rm -rf /opt/miniconda-for-velox/
#          cd ep/build-velox/src && \
#          ./get_velox.sh
#          cd ../build/velox_ep/
#          source /opt/rh/gcc-toolset-9/enable
#          make EXTRA_CMAKE_FLAGS="-DVELOX_ENABLE_PARQUET=ON -DVELOX_BUILD_TESTING=ON -DVELOX_BUILD_TEST_UTILS=ON"
#
#      - name: CCache after
#        run: |
#          ccache -s
#
#      - uses: actions/cache/save@v3
#        with:
#          path: '${{ env.CCACHE_DIR }}'
#          key: ccache-centos-release-default
