# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Velox backend nightly release

on:
  pull_request:
    paths:
      - '.github/workflows/velox_nightly.yml'
  schedule:
    - cron: '0 0 * * *'

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  CCACHE_DIR: "${{ github.workspace }}/.ccache"
  SETUP: 'bash .github/workflows/util/setup_helper.sh'

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-native-lib:
    if: ${{ startsWith(github.repository, 'apache/') }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Get Ccache
        uses: actions/cache/restore@v4
        with:
          path: '${{ env.CCACHE_DIR }}'
          key: ccache-centos7-release-default-${{github.sha}}
          restore-keys: |
            ccache-centos7-release-default
      - name: Build Gluten velox third party
        run: |
          docker run -v $GITHUB_WORKSPACE:/work -w /work apache/gluten:vcpkg-centos-7 bash -c "
            df -a
            cd /work
            export CCACHE_DIR=/work/.ccache
            bash dev/ci-velox-buildstatic-centos-7.sh
            ccache -s
            mkdir -p /work/.m2/repository/org/apache/arrow/
            cp -r /root/.m2/repository/org/apache/arrow/* /work/.m2/repository/org/apache/arrow/
          "
      - name: Upload native libs
        uses: actions/upload-artifact@v4
        with:
          path: ./cpp/build/releases/
          name: velox-native-lib-${{github.sha}}
          retention-days: 1
      - name: Upload Artifact Arrow Jar
        uses: actions/upload-artifact@v4
        with:
          path: .m2/repository/org/apache/arrow/
          name: velox-arrow-jar-centos-7-${{github.sha}}

  build-bundle-package-centos8-jdk8:
    needs: build-native-lib
    runs-on: ubuntu-22.04
    container: centos:8
    steps:
      - uses: actions/checkout@v4
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          name: velox-native-lib-${{github.sha}}
          path: ./cpp/build/releases
      - name: Download All Arrow Jar Artifacts
        uses: actions/download-artifact@v4
        with:
          name: velox-arrow-jar-centos-7-${{github.sha}}
          path: /root/.m2/repository/org/apache/arrow/
      - name: Setup java and maven
        run: |
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* && \
          yum update -y && yum install -y java-1.8.0-openjdk-devel wget
          $SETUP install_maven
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Build package for Spark
        run: |
          cd $GITHUB_WORKSPACE/ && \
          export MAVEN_HOME=/usr/lib/maven && \
          export PATH=${PATH}:${MAVEN_HOME}/bin && \
          mvn clean install -Pspark-3.2 -Pbackends-velox -Pceleborn -Puniffle -DskipTests -Dmaven.source.skip
          mvn clean install -Pspark-3.3 -Pbackends-velox -Pceleborn -Puniffle -DskipTests -Dmaven.source.skip
          mvn clean install -Pspark-3.4 -Pbackends-velox -Pceleborn -Puniffle -DskipTests -Dmaven.source.skip
          mvn clean install -Pspark-3.5 -Pbackends-velox -Pceleborn -Puniffle -DskipTests -Dmaven.source.skip
      - name: Upload bundle package
        uses: actions/upload-artifact@v4
        with:
          name: nightly-gluten-velox-bundle-package-jdk8-${{ steps.date.outputs.date }}
          path: package/target/gluten-velox-bundle-*.jar
          retention-days: 7
      - name: rsync to apache nightly
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr
          path: package/target/gluten-velox-bundle-*.jar
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/gluten/nightly-release-jdk8
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}

  build-bundle-package-centos8-jdk17:
    needs: build-native-lib
    runs-on: ubuntu-22.04
    container: centos:8
    steps:
      - uses: actions/checkout@v4
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          name: velox-native-lib-${{github.sha}}
          path: ./cpp/build/releases
      - name: Download All Arrow Jar Artifacts
        uses: actions/download-artifact@v4
        with:
          name: velox-arrow-jar-centos-7-${{github.sha}}
          path: /root/.m2/repository/org/apache/arrow/
      - name: Setup java and maven
        run: |
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* && \
          yum update -y && yum install -y java-17-openjdk-devel wget
          $SETUP install_maven
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Build package for Spark
        run: |
          cd $GITHUB_WORKSPACE/ && \
          export MAVEN_HOME=/usr/lib/maven && \
          export PATH=${PATH}:${MAVEN_HOME}/bin && \
          mvn clean install -Pspark-3.4 -Pjava-17 -Pbackends-velox -Pceleborn -Puniffle -Piceberg -Phudi -Pdelta -DskipTests -Dmaven.source.skip
          mvn clean install -Pspark-3.5 -Pjava-17 -Pbackends-velox -Pceleborn -Puniffle -Piceberg -Phudi -Pdelta -DskipTests -Dmaven.source.skip
      - name: Upload bundle package
        uses: actions/upload-artifact@v4
        with:
          name: nightly-gluten-velox-bundle-package-jdk17-${{ steps.date.outputs.date }}
          path: package/target/gluten-velox-bundle-*.jar
          retention-days: 7
      - name: rsync to apache nightly
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr
          path: package/target/gluten-velox-bundle-*.jar
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/gluten/nightly-release-jdk17
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}


  #TODO: split ARM section into different file
  build-native-lib-centos-8-arm64:
    runs-on: ubuntu-24.04-arm
    container: apache/gluten:vcpkg-centos-8
    steps:
      - uses: actions/checkout@v4
      - name: Get Ccache
        uses: actions/cache/restore@v4
        with:
          path: '${{ env.CCACHE_DIR }}'
          key: ccache-centos8-release-default-${{runner.arch}}-${{github.sha}}
          restore-keys: |
            ccache-centos8-release-default-${{runner.arch}}
      - name: Build Gluten native libraries
        run: |
          df -a
          bash dev/ci-velox-buildstatic-centos-8.sh
          ccache -s
          mkdir -p $GITHUB_WORKSPACE/.m2/repository/org/apache/arrow/
          cp -r /root/.m2/repository/org/apache/arrow/* $GITHUB_WORKSPACE/.m2/repository/org/apache/arrow/
      - name: "Save ccache"
        uses: actions/cache/save@v4
        id: ccache
        with:
          path: '${{ env.CCACHE_DIR }}'
          key: ccache-centos8-release-default-${{runner.arch}}-${{github.sha}}
      - uses: actions/upload-artifact@v4
        with:
          name: velox-native-lib-centos-8-${{github.sha}}
          path: ./cpp/build/releases/
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: velox-arrow-jar-centos-8-${{github.sha}}
          path: .m2/repository/org/apache/arrow/
          if-no-files-found: error

  build-bundle-package-centos8-jdk8-arm64:
    needs: build-native-lib-centos-8-arm64
    runs-on: ubuntu-22.04-arm
    container: centos:8
    steps:
      - uses: actions/checkout@v4
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          name: velox-native-lib-centos-8-${{github.sha}}
          path: ./cpp/build/releases
      - name: Download All Arrow Jar Artifacts
        uses: actions/download-artifact@v4
        with:
          name: velox-arrow-jar-centos-8-${{github.sha}}
          path: /root/.m2/repository/org/apache/arrow/
      - name: Setup java and maven
        run: |
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* && \
          yum update -y && yum install -y java-1.8.0-openjdk-devel wget
          $SETUP install_maven
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Build package for Spark
        run: |
          cd $GITHUB_WORKSPACE/ && \
          export MAVEN_HOME=/usr/lib/maven && \
          export PATH=${PATH}:${MAVEN_HOME}/bin && \
          mvn clean install -Pspark-3.2 -Pbackends-velox -Pceleborn -Puniffle -DskipTests -Dmaven.source.skip
          mvn clean install -Pspark-3.3 -Pbackends-velox -Pceleborn -Puniffle -DskipTests -Dmaven.source.skip
          mvn clean install -Pspark-3.4 -Pbackends-velox -Pceleborn -Puniffle -DskipTests -Dmaven.source.skip
          mvn clean install -Pspark-3.5 -Pbackends-velox -Pceleborn -Puniffle -DskipTests -Dmaven.source.skip
      - name: Upload bundle package
        uses: actions/upload-artifact@v4
        with:
          name: nightly-gluten-velox-bundle-package-jdk8-arm64-${{ steps.date.outputs.date }}
          path: package/target/gluten-velox-bundle-*.jar
          retention-days: 7

  build-bundle-package-centos8-jdk17-arm64:
    needs: build-native-lib-centos-8-arm64
    runs-on: ubuntu-22.04-arm
    container: centos:8
    steps:
      - uses: actions/checkout@v4
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          name: velox-native-lib-centos-8-${{github.sha}}
          path: ./cpp/build/releases
      - name: Download All Arrow Jar Artifacts
        uses: actions/download-artifact@v4
        with:
          name: velox-arrow-jar-centos-8-${{github.sha}}
          path: /root/.m2/repository/org/apache/arrow/
      - name: Setup java and maven
        run: |
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* && \
          yum update -y && yum install -y java-17-openjdk-devel wget
          $SETUP install_maven
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Build package for Spark
        run: |
          cd $GITHUB_WORKSPACE/ && \
          export MAVEN_HOME=/usr/lib/maven && \
          export PATH=${PATH}:${MAVEN_HOME}/bin && \
          mvn clean install -Pspark-3.4 -Pjava-17 -Pbackends-velox -Pceleborn -Puniffle -Piceberg -Phudi -Pdelta -DskipTests -Dmaven.source.skip
          mvn clean install -Pspark-3.5 -Pjava-17 -Pbackends-velox -Pceleborn -Puniffle -Piceberg -Phudi -Pdelta -DskipTests -Dmaven.source.skip
      - name: Upload bundle package
        uses: actions/upload-artifact@v4
        with:
          name: nightly-gluten-velox-bundle-package-jdk17-arm64-${{ steps.date.outputs.date }}
          path: package/target/gluten-velox-bundle-*.jar
          retention-days: 7

  upload-jdk8-package-arm64:
    needs: [build-bundle-package-centos8-jdk8-arm64]
    runs-on: ubuntu-22.04
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Download JDK8 Package Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nightly-gluten-velox-bundle-package-jdk8-arm64-${{ steps.date.outputs.date }}
          path: package/
      - name: rsync to apache nightly
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr
          path: package/gluten-velox-bundle-*.jar
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/gluten/nightly-release-jdk8
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}

  upload-jdk17-package-arm64:
    needs: [build-bundle-package-centos8-jdk17-arm64]
    runs-on: ubuntu-22.04
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Download JDK17 Package Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nightly-gluten-velox-bundle-package-jdk17-arm64-${{ steps.date.outputs.date }}
          path: package/
      - name: rsync to apache nightly
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr
          path: package/gluten-velox-bundle-*.jar
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/gluten/nightly-release-jdk17
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}